export const signatures = [
    { handle: "satyanadella", location: "California, USA", message: "I love live share 2" },
    { handle: "scottgu", location: "California, USA", message: "I love live share 2" },
    { handle: "samjgeorge", location: "California, USA", message: "I love live share 2" },
    { handle: "lostintangent", location: "Washington, USA", message: "I love live share" },
    { handle: "amandaksilver", location: "Washington, USA", message: "I love live share" },
    { handle: "DonovanBrown", location: "Washington, USA", message: "I love live share" },
    { handle: "shanselman", location: "Washington, USA", message: "I love live share" },
    { handle: "chuxel", location: "Minnesota, USA", message: "This is so coool!!!  Go Vikings!" },
    { handle: "legomushroom", location: "California, USA", message: "I love live share 2" },
    { handle: "jonwchu", location: "California, USA", message: "I love live share 2" },
    { handle: "bradygaster", location: "California, USA", message: "I love live share 2" },
    { handle: "simcalv", location: "California, USA", message: "I love live share 2" },
    { handle: "davidkpiano", location: "California, USA", message: "I love live share 2" },
    { handle: "johnmont", location: "California, USA", message: "I love live share 2" },
    { handle: "chrisdias", location: "California, USA", message: "I love live share 2" },
    { handle: "nz_sean", location: "California, USA", message: "I love live share 2" },
    { handle: "erichgamma", location: "California, USA", message: "I love live share 2" },
    { handle: "pjmeyer", location: "California, USA", message: "I love live share 2" },
    { handle: "srivatsn", location: "California, USA", message: "I love live share 2" },
    { handle: "auchenberg", location: "California, USA", message: "I love live share 2" },
    { handle: "weinand", location: "California, USA", message: "I love live share 2" },
    { handle: "kaimaetzel", location: "California, USA", message: "I love live share 2" },
    { handle: "dougam", location: "California, USA", message: "I love live share 2" },
    { handle: "julwhite", location: "California, USA", message: "I love live share 2" },
    { handle: "kuhlenhuth", location: "California, USA", message: "I love live share 2" },
    { handle: "jeffhollan", location: "California, USA", message: "I love live share 2" },
    { handle: "andysterland", location: "California, USA", message: "I love live share 2" },
    { handle: "dhopton_ms", location: "California, USA", message: "I love live share 2" },
    { handle: "jlzander", location: "California, USA", message: "I love live share 2" },
    { handle: "markrussinovich", location: "California, USA", message: "I love live share 2" },
    { handle: "jsnover", location: "California, USA", message: "PowerShell FTW!!!" },
    { handle: "gabrtv", location: "Boulder", message: "I love live share 2" },
    { handle: "brendandburns", location: "California, USA", message: "k8s baby!!" },
    { handle: "dynamicwebpaige", location: "California, USA", message: "I love live share 2" },
    { handle: "mattbierner", location: "California, USA", message: "I love live share 2" },
    { handle: "johannesrieken", location: "Zurich", message: "Zurich is beautiful this time of year..." },
    { handle: "csharpfritz", location: "Boston", message: "If you need me, I'll be on Twitch..." },
    { handle: "damianedwards", location: "Seattle", message: "ASP.NET Core is so cool" },
    { handle: "MarkPavWT", location: "California, USA", message: "CodeLens is now in VS Community Edition!!!" },
    { handle: "acangialosi", location: "California, USA", message: "CD4VS" },
    { handle: "fiveisprime", location: "California, USA", message: "Azure Tools in VS Code!!" },
    { handle: "AbelSquidHead", location: "Seattle", message: "Rockin with DevOps!" },
    { handle: "bketelsen", location: "Tampa", message: "Knitter of Azure Hats" },
    { handle: "dandttaylor", location: "Seattle", message: "Check out the Python tools!" },
    { handle: "ChenDeborah", location: "Seattle", message: "Check out IntelliCode!" },
    { handle: "vrtinch", location: "Detroit", message: "I am the code MASTA!!!!" },
    { handle: "mkrain4", location: "Seattle", message: "Was Here :D" },
    { handle: "maximzhuk", location: "Los Angeles", message: "Go to Space :)" },
    { handle: "aaronfriel", location: "Des Moines, IA", message: "Better than Wave" },
    { handle: "jemiahsius", location: "Miami", message: "Nice for what?" },
    { handle: "threesevenths", location: "Toronto, Canada", message: "Awesome, Just Awesome!" },
    { handle: "tyriar", location: "Seattle", message: "Dude that Terminal!" },
    { handle: "joni", location: "Seattle", message: "Thats Cool!" },
    { handle: "davincij15", location: "Chile", message: "Live Share is a game changer for teams!" },
    { handle: "cynthiar", location: "Seattle", message: "Nice Demo!" },
    { handle: "SoWaky", location: "Chicago", message: "Collaboration Rocks!" },
    { handle: "oasisofspades", location: "Atlanta", message: "Almost didn't find this demo!" },
    { handle: "twnick", location: "Los Angeles", message: "I found a bug..." },
    { handle: "drewpfeif", location: "Phoenix", message: "I love live share" }
];